import { createStyles } from '../theme'

export default createStyles(theme => ({
  // Background Colors
  bgPrimary: { backgroundColor: theme.colors.primary },
  bgPrimaryLight: { backgroundColor: theme.colors.primaryLight },
  bgPrimaryDark: { backgroundColor: theme.colors.primaryDark },
  bgPrimaryContrast: { backgroundColor: theme.colors.primaryContrast },
  bgSecondary: { backgroundColor: theme.colors.secondary },
  bgSecondaryLight: { backgroundColor: theme.colors.secondaryLight },
  bgSecondaryDark: { backgroundColor: theme.colors.secondaryDark },
  bgSecondaryContrast: { backgroundColor: theme.colors.secondaryContrast },
  bgInfo: { backgroundColor: theme.colors.info },
  bgInfoLight: { backgroundColor: theme.colors.infoLight },
  bgInfoDark: { backgroundColor: theme.colors.infoDark },
  bgInfoContrast: { backgroundColor: theme.colors.infoContrast },
  bgSuccess: { backgroundColor: theme.colors.success },
  bgSuccessLight: { backgroundColor: theme.colors.successLight },
  bgSuccessDark: { backgroundColor: theme.colors.successDark },
  bgSuccessContrast: { backgroundColor: theme.colors.successContrast },
  bgError: { backgroundColor: theme.colors.error },
  bgErrorLight: { backgroundColor: theme.colors.errorLight },
  bgErrorDark: { backgroundColor: theme.colors.errorDark },
  bgErrorContrast: { backgroundColor: theme.colors.errorContrast },
  bgWarning: { backgroundColor: theme.colors.warning },
  bgWarningLight: { backgroundColor: theme.colors.warningLight },
  bgWarningDark: { backgroundColor: theme.colors.warningDark },
  bgWarningContrast: { backgroundColor: theme.colors.warningContrast },
  bgPaper: { backgroundColor: theme.colors.paper },
  bgSelected: { backgroundColor: theme.colors.selected },
  bgDisabled: { backgroundColor: theme.colors.disabled },
  bgFocused: { backgroundColor: theme.colors.focused },
  bgMuted: { backgroundColor: theme.colors.muted },
  bgWhite: { backgroundColor: theme.colors.white },
  bgGray100: { backgroundColor: theme.colors.gray100 },
  bgGray200: { backgroundColor: theme.colors.gray200 },
  bgGray300: { backgroundColor: theme.colors.gray300 },
  bgGray400: { backgroundColor: theme.colors.gray400 },
  bgGray500: { backgroundColor: theme.colors.gray500 },
  bgGray600: { backgroundColor: theme.colors.gray600 },
  bgGray700: { backgroundColor: theme.colors.gray700 },
  bgGray800: { backgroundColor: theme.colors.gray800 },
  bgGray900: { backgroundColor: theme.colors.gray900 },
  bgBlack: { backgroundColor: theme.colors.black },
  bgTransparent: { backgroundColor: theme.colors.transparent }
}))
