import { createStyles } from '../theme'

export default createStyles(theme => ({
  // Display
  flex: { display: 'flex' },
  hidden: { display: 'none' },
  // Object Fit
  objectContain: { resizeMode: 'contain' },
  objectCover: { resizeMode: 'cover' },
  objectStretch: { resizeMode: 'stretch' },
  objectCenter: { resizeMode: 'center' },
  objectRepeat: { resizeMode: 'repeat' },
  resizeContain: { resizeMode: 'contain' },
  resizeCover: { resizeMode: 'cover' },
  resizeStretch: { resizeMode: 'stretch' },
  resizeCenter: { resizeMode: 'center' },
  resizeRepeat: { resizeMode: 'repeat' },
  // Overflow
  overflowVisible: { overflow: 'visible' },
  overflowHidden: { overflow: 'hidden' },
  // Position
  relative: { position: 'relative' },
  absolute: { position: 'absolute' },
  // Top / Right / Bottom / Left
  inset0: { top: theme.spacing[0], bottom: theme.spacing[0], left: theme.spacing[0], right: theme.spacing[0] },
  insetPx: { top: theme.spacing.px, bottom: theme.spacing.px, left: theme.spacing.px, right: theme.spacing.px },
  inset0_5: {
    top: theme.spacing[0.5],
    bottom: theme.spacing[0.5],
    left: theme.spacing[0.5],
    right: theme.spacing[0.5]
  },
  inset1: { top: theme.spacing[1], bottom: theme.spacing[1], left: theme.spacing[1], right: theme.spacing[1] },
  inset2: { top: theme.spacing[2], bottom: theme.spacing[2], left: theme.spacing[2], right: theme.spacing[2] },
  inset3: { top: theme.spacing[3], bottom: theme.spacing[3], left: theme.spacing[3], right: theme.spacing[3] },
  inset4: { top: theme.spacing[4], bottom: theme.spacing[4], left: theme.spacing[4], right: theme.spacing[4] },
  inset5: { top: theme.spacing[5], bottom: theme.spacing[5], left: theme.spacing[5], right: theme.spacing[5] },
  inset6: { top: theme.spacing[6], bottom: theme.spacing[6], left: theme.spacing[6], right: theme.spacing[6] },
  inset7: { top: theme.spacing[7], bottom: theme.spacing[7], left: theme.spacing[7], right: theme.spacing[7] },
  inset8: { top: theme.spacing[8], bottom: theme.spacing[8], left: theme.spacing[8], right: theme.spacing[8] },
  inset9: { top: theme.spacing[9], bottom: theme.spacing[9], left: theme.spacing[9], right: theme.spacing[9] },
  inset10: { top: theme.spacing[10], bottom: theme.spacing[10], left: theme.spacing[10], right: theme.spacing[10] },
  inset11: { top: theme.spacing[11], bottom: theme.spacing[11], left: theme.spacing[11], right: theme.spacing[11] },
  inset12: { top: theme.spacing[12], bottom: theme.spacing[12], left: theme.spacing[12], right: theme.spacing[12] },
  inset14: { top: theme.spacing[14], bottom: theme.spacing[14], left: theme.spacing[14], right: theme.spacing[14] },
  inset16: { top: theme.spacing[16], bottom: theme.spacing[16], left: theme.spacing[16], right: theme.spacing[16] },
  inset20: { top: theme.spacing[20], bottom: theme.spacing[20], left: theme.spacing[20], right: theme.spacing[20] },
  inset24: { top: theme.spacing[24], bottom: theme.spacing[24], left: theme.spacing[24], right: theme.spacing[24] },
  inset28: { top: theme.spacing[28], bottom: theme.spacing[28], left: theme.spacing[28], right: theme.spacing[28] },
  inset32: { top: theme.spacing[32], bottom: theme.spacing[32], left: theme.spacing[32], right: theme.spacing[32] },
  inset36: { top: theme.spacing[36], bottom: theme.spacing[36], left: theme.spacing[36], right: theme.spacing[36] },
  inset40: { top: theme.spacing[40], bottom: theme.spacing[40], left: theme.spacing[40], right: theme.spacing[40] },
  inset44: { top: theme.spacing[44], bottom: theme.spacing[44], left: theme.spacing[44], right: theme.spacing[44] },
  inset48: { top: theme.spacing[48], bottom: theme.spacing[48], left: theme.spacing[48], right: theme.spacing[48] },
  inset52: { top: theme.spacing[52], bottom: theme.spacing[52], left: theme.spacing[52], right: theme.spacing[52] },
  inset56: { top: theme.spacing[56], bottom: theme.spacing[56], left: theme.spacing[56], right: theme.spacing[56] },
  inset60: { top: theme.spacing[60], bottom: theme.spacing[60], left: theme.spacing[60], right: theme.spacing[60] },
  inset64: { top: theme.spacing[64], bottom: theme.spacing[64], left: theme.spacing[64], right: theme.spacing[64] },
  inset72: { top: theme.spacing[72], bottom: theme.spacing[72], left: theme.spacing[72], right: theme.spacing[72] },
  inset80: { top: theme.spacing[80], bottom: theme.spacing[80], left: theme.spacing[80], right: theme.spacing[80] },
  inset96: { top: theme.spacing[96], bottom: theme.spacing[96], left: theme.spacing[96], right: theme.spacing[96] },
  inset1_2: { top: '50%', bottom: '50%', left: '50%', right: '50%' },
  inset1_3: { top: '33.333333%', bottom: '33.333333%', left: '33.333333%', right: '33.333333%' },
  inset2_3: { top: '66.666667%', bottom: '66.666667%', left: '66.666667%', right: '66.666667%' },
  inset1_4: { top: '25%', bottom: '25%', left: '25%', right: '25%' },
  inset2_4: { top: '50%', bottom: '50%', left: '50%', right: '50%' },
  inset3_4: { top: '75%', bottom: '75%', left: '75%', right: '75%' },
  inset1_5: { top: '20%', bottom: '20%', left: '20%', right: '20%' },
  inset2_5: { top: '40%', bottom: '40%', left: '40%', right: '40%' },
  inset3_5: { top: '60%', bottom: '60%', left: '60%', right: '60%' },
  inset4_5: { top: '80%', bottom: '80%', left: '80%', right: '80%' },
  insetY0: { top: theme.spacing[0], bottom: theme.spacing[0] },
  insetYPx: { top: theme.spacing.px, bottom: theme.spacing.px },
  insetY0_5: { top: theme.spacing[0.5], bottom: theme.spacing[0.5] },
  insetY1: { top: theme.spacing[1], bottom: theme.spacing[1] },
  insetY2: { top: theme.spacing[2], bottom: theme.spacing[2] },
  insetY3: { top: theme.spacing[3], bottom: theme.spacing[3] },
  insetY4: { top: theme.spacing[4], bottom: theme.spacing[4] },
  insetY5: { top: theme.spacing[5], bottom: theme.spacing[5] },
  insetY6: { top: theme.spacing[6], bottom: theme.spacing[6] },
  insetY7: { top: theme.spacing[7], bottom: theme.spacing[7] },
  insetY8: { top: theme.spacing[8], bottom: theme.spacing[8] },
  insetY9: { top: theme.spacing[9], bottom: theme.spacing[9] },
  insetY10: { top: theme.spacing[10], bottom: theme.spacing[10] },
  insetY11: { top: theme.spacing[11], bottom: theme.spacing[11] },
  insetY12: { top: theme.spacing[12], bottom: theme.spacing[12] },
  insetY14: { top: theme.spacing[14], bottom: theme.spacing[14] },
  insetY16: { top: theme.spacing[16], bottom: theme.spacing[16] },
  insetY20: { top: theme.spacing[20], bottom: theme.spacing[20] },
  insetY24: { top: theme.spacing[24], bottom: theme.spacing[24] },
  insetY28: { top: theme.spacing[28], bottom: theme.spacing[28] },
  insetY32: { top: theme.spacing[32], bottom: theme.spacing[32] },
  insetY36: { top: theme.spacing[36], bottom: theme.spacing[36] },
  insetY40: { top: theme.spacing[40], bottom: theme.spacing[40] },
  insetY44: { top: theme.spacing[44], bottom: theme.spacing[44] },
  insetY48: { top: theme.spacing[48], bottom: theme.spacing[48] },
  insetY52: { top: theme.spacing[52], bottom: theme.spacing[52] },
  insetY56: { top: theme.spacing[56], bottom: theme.spacing[56] },
  insetY60: { top: theme.spacing[60], bottom: theme.spacing[60] },
  insetY64: { top: theme.spacing[64], bottom: theme.spacing[64] },
  insetY72: { top: theme.spacing[72], bottom: theme.spacing[72] },
  insetY80: { top: theme.spacing[80], bottom: theme.spacing[80] },
  insetY96: { top: theme.spacing[96], bottom: theme.spacing[96] },
  insetX0: { left: theme.spacing[0], right: theme.spacing[0] },
  insetXPx: { left: theme.spacing.px, right: theme.spacing.px },
  insetX0_5: { left: theme.spacing[0.5], right: theme.spacing[0.5] },
  insetX1: { left: theme.spacing[1], right: theme.spacing[1] },
  insetX2: { left: theme.spacing[2], right: theme.spacing[2] },
  insetX3: { left: theme.spacing[3], right: theme.spacing[3] },
  insetX4: { left: theme.spacing[4], right: theme.spacing[4] },
  insetX5: { left: theme.spacing[5], right: theme.spacing[5] },
  insetX6: { left: theme.spacing[6], right: theme.spacing[6] },
  insetX7: { left: theme.spacing[7], right: theme.spacing[7] },
  insetX8: { left: theme.spacing[8], right: theme.spacing[8] },
  insetX9: { left: theme.spacing[9], right: theme.spacing[9] },
  insetX10: { left: theme.spacing[10], right: theme.spacing[10] },
  insetX11: { left: theme.spacing[11], right: theme.spacing[11] },
  insetX12: { left: theme.spacing[12], right: theme.spacing[12] },
  insetX14: { left: theme.spacing[14], right: theme.spacing[14] },
  insetX16: { left: theme.spacing[16], right: theme.spacing[16] },
  insetX20: { left: theme.spacing[20], right: theme.spacing[20] },
  insetX24: { left: theme.spacing[24], right: theme.spacing[24] },
  insetX28: { left: theme.spacing[28], right: theme.spacing[28] },
  insetX32: { left: theme.spacing[32], right: theme.spacing[32] },
  insetX36: { left: theme.spacing[36], right: theme.spacing[36] },
  insetX40: { left: theme.spacing[40], right: theme.spacing[40] },
  insetX44: { left: theme.spacing[44], right: theme.spacing[44] },
  insetX48: { left: theme.spacing[48], right: theme.spacing[48] },
  insetX52: { left: theme.spacing[52], right: theme.spacing[52] },
  insetX56: { left: theme.spacing[56], right: theme.spacing[56] },
  insetX60: { left: theme.spacing[60], right: theme.spacing[60] },
  insetX64: { left: theme.spacing[64], right: theme.spacing[64] },
  insetX72: { left: theme.spacing[72], right: theme.spacing[72] },
  insetX80: { left: theme.spacing[80], right: theme.spacing[80] },
  insetX96: { left: theme.spacing[96], right: theme.spacing[96] },
  top0: { top: theme.spacing[0] },
  topPx: { top: theme.spacing.px },
  top0_5: { top: theme.spacing[0.5] },
  top1: { top: theme.spacing[1] },
  top2: { top: theme.spacing[2] },
  top3: { top: theme.spacing[3] },
  top4: { top: theme.spacing[4] },
  top5: { top: theme.spacing[5] },
  top6: { top: theme.spacing[6] },
  top7: { top: theme.spacing[7] },
  top8: { top: theme.spacing[8] },
  top9: { top: theme.spacing[9] },
  top10: { top: theme.spacing[10] },
  top11: { top: theme.spacing[11] },
  top12: { top: theme.spacing[12] },
  top14: { top: theme.spacing[14] },
  top16: { top: theme.spacing[16] },
  top20: { top: theme.spacing[20] },
  top24: { top: theme.spacing[24] },
  top28: { top: theme.spacing[28] },
  top32: { top: theme.spacing[32] },
  top36: { top: theme.spacing[36] },
  top40: { top: theme.spacing[40] },
  top44: { top: theme.spacing[44] },
  top48: { top: theme.spacing[48] },
  top52: { top: theme.spacing[52] },
  top56: { top: theme.spacing[56] },
  top60: { top: theme.spacing[60] },
  top64: { top: theme.spacing[64] },
  top72: { top: theme.spacing[72] },
  top80: { top: theme.spacing[80] },
  top96: { top: theme.spacing[96] },
  top1_2: { top: '50%' },
  top1_3: { top: '33.333333%' },
  top2_3: { top: '66.666667%' },
  top1_4: { top: '25%' },
  top2_4: { top: '50%' },
  top3_4: { top: '75%' },
  top1_5: { top: '20%' },
  top2_5: { top: '40%' },
  top3_5: { top: '60%' },
  top4_5: { top: '80%' },
  right0: { right: theme.spacing[0] },
  rightPx: { right: theme.spacing.px },
  right0_5: { right: theme.spacing[0.5] },
  right1: { right: theme.spacing[1] },
  right2: { right: theme.spacing[2] },
  right3: { right: theme.spacing[3] },
  right4: { right: theme.spacing[4] },
  right5: { right: theme.spacing[5] },
  right6: { right: theme.spacing[6] },
  right7: { right: theme.spacing[7] },
  right8: { right: theme.spacing[8] },
  right9: { right: theme.spacing[9] },
  right10: { right: theme.spacing[10] },
  right11: { right: theme.spacing[11] },
  right12: { right: theme.spacing[12] },
  right14: { right: theme.spacing[14] },
  right16: { right: theme.spacing[16] },
  right20: { right: theme.spacing[20] },
  right24: { right: theme.spacing[24] },
  right28: { right: theme.spacing[28] },
  right32: { right: theme.spacing[32] },
  right36: { right: theme.spacing[36] },
  right40: { right: theme.spacing[40] },
  right44: { right: theme.spacing[44] },
  right48: { right: theme.spacing[48] },
  right52: { right: theme.spacing[52] },
  right56: { right: theme.spacing[56] },
  right60: { right: theme.spacing[60] },
  right64: { right: theme.spacing[64] },
  right72: { right: theme.spacing[72] },
  right80: { right: theme.spacing[80] },
  right96: { right: theme.spacing[96] },
  right1_2: { right: '50%' },
  right1_3: { right: '33.333333%' },
  right2_3: { right: '66.666667%' },
  right1_4: { right: '25%' },
  right2_4: { right: '50%' },
  right3_4: { right: '75%' },
  right1_5: { right: '20%' },
  right2_5: { right: '40%' },
  right3_5: { right: '60%' },
  right4_5: { right: '80%' },
  bottom0: { bottom: theme.spacing[0] },
  bottomPx: { bottom: theme.spacing.px },
  bottom0_5: { bottom: theme.spacing[0.5] },
  bottom1: { bottom: theme.spacing[1] },
  bottom2: { bottom: theme.spacing[2] },
  bottom3: { bottom: theme.spacing[3] },
  bottom4: { bottom: theme.spacing[4] },
  bottom5: { bottom: theme.spacing[5] },
  bottom6: { bottom: theme.spacing[6] },
  bottom7: { bottom: theme.spacing[7] },
  bottom8: { bottom: theme.spacing[8] },
  bottom9: { bottom: theme.spacing[9] },
  bottom10: { bottom: theme.spacing[10] },
  bottom11: { bottom: theme.spacing[11] },
  bottom12: { bottom: theme.spacing[12] },
  bottom14: { bottom: theme.spacing[14] },
  bottom16: { bottom: theme.spacing[16] },
  bottom20: { bottom: theme.spacing[20] },
  bottom24: { bottom: theme.spacing[24] },
  bottom28: { bottom: theme.spacing[28] },
  bottom32: { bottom: theme.spacing[32] },
  bottom36: { bottom: theme.spacing[36] },
  bottom40: { bottom: theme.spacing[40] },
  bottom44: { bottom: theme.spacing[44] },
  bottom48: { bottom: theme.spacing[48] },
  bottom52: { bottom: theme.spacing[52] },
  bottom56: { bottom: theme.spacing[56] },
  bottom60: { bottom: theme.spacing[60] },
  bottom64: { bottom: theme.spacing[64] },
  bottom72: { bottom: theme.spacing[72] },
  bottom80: { bottom: theme.spacing[80] },
  bottom96: { bottom: theme.spacing[96] },
  bottom1_2: { bottom: '50%' },
  bottom1_3: { bottom: '33.333333%' },
  bottom2_3: { bottom: '66.666667%' },
  bottom1_4: { bottom: '25%' },
  bottom2_4: { bottom: '50%' },
  bottom3_4: { bottom: '75%' },
  bottom1_5: { bottom: '20%' },
  bottom2_5: { bottom: '40%' },
  bottom3_5: { bottom: '60%' },
  bottom4_5: { bottom: '80%' },
  left0: { left: theme.spacing[0] },
  leftPx: { left: theme.spacing.px },
  left0_5: { left: theme.spacing[0.5] },
  left1: { left: theme.spacing[1] },
  left2: { left: theme.spacing[2] },
  left3: { left: theme.spacing[3] },
  left4: { left: theme.spacing[4] },
  left5: { left: theme.spacing[5] },
  left6: { left: theme.spacing[6] },
  left7: { left: theme.spacing[7] },
  left8: { left: theme.spacing[8] },
  left9: { left: theme.spacing[9] },
  left10: { left: theme.spacing[10] },
  left11: { left: theme.spacing[11] },
  left12: { left: theme.spacing[12] },
  left14: { left: theme.spacing[14] },
  left16: { left: theme.spacing[16] },
  left20: { left: theme.spacing[20] },
  left24: { left: theme.spacing[24] },
  left28: { left: theme.spacing[28] },
  left32: { left: theme.spacing[32] },
  left36: { left: theme.spacing[36] },
  left40: { left: theme.spacing[40] },
  left44: { left: theme.spacing[44] },
  left48: { left: theme.spacing[48] },
  left52: { left: theme.spacing[52] },
  left56: { left: theme.spacing[56] },
  left60: { left: theme.spacing[60] },
  left64: { left: theme.spacing[64] },
  left72: { left: theme.spacing[72] },
  left80: { left: theme.spacing[80] },
  left96: { left: theme.spacing[96] },
  left1_2: { left: '50%' },
  left1_3: { left: '33.333333%' },
  left2_3: { left: '66.666667%' },
  left1_4: { left: '25%' },
  left2_4: { left: '50%' },
  left3_4: { left: '75%' },
  left1_5: { left: '20%' },
  left2_5: { left: '40%' },
  left3_5: { left: '60%' },
  left4_5: { left: '80%' },
  start0: { start: theme.spacing[0] },
  startPx: { start: theme.spacing.px },
  start0_5: { start: theme.spacing[0.5] },
  start1: { start: theme.spacing[1] },
  start2: { start: theme.spacing[2] },
  start3: { start: theme.spacing[3] },
  start4: { start: theme.spacing[4] },
  start5: { start: theme.spacing[5] },
  start6: { start: theme.spacing[6] },
  start7: { start: theme.spacing[7] },
  start8: { start: theme.spacing[8] },
  start9: { start: theme.spacing[9] },
  start10: { start: theme.spacing[10] },
  start11: { start: theme.spacing[11] },
  start12: { start: theme.spacing[12] },
  start14: { start: theme.spacing[14] },
  start16: { start: theme.spacing[16] },
  start20: { start: theme.spacing[20] },
  start24: { start: theme.spacing[24] },
  start28: { start: theme.spacing[28] },
  start32: { start: theme.spacing[32] },
  start36: { start: theme.spacing[36] },
  start40: { start: theme.spacing[40] },
  start44: { start: theme.spacing[44] },
  start48: { start: theme.spacing[48] },
  start52: { start: theme.spacing[52] },
  start56: { start: theme.spacing[56] },
  start60: { start: theme.spacing[60] },
  start64: { start: theme.spacing[64] },
  start72: { start: theme.spacing[72] },
  start80: { start: theme.spacing[80] },
  start96: { start: theme.spacing[96] },
  start1_2: { start: '50%' },
  start1_3: { start: '33.333333%' },
  start2_3: { start: '66.666667%' },
  start1_4: { start: '25%' },
  start2_4: { start: '50%' },
  start3_4: { start: '75%' },
  start1_5: { start: '20%' },
  start2_5: { start: '40%' },
  start3_5: { start: '60%' },
  start4_5: { start: '80%' },
  end0: { end: theme.spacing[0] },
  endPx: { end: theme.spacing.px },
  end0_5: { end: theme.spacing[0.5] },
  end1: { end: theme.spacing[1] },
  end2: { end: theme.spacing[2] },
  end3: { end: theme.spacing[3] },
  end4: { end: theme.spacing[4] },
  end5: { end: theme.spacing[5] },
  end6: { end: theme.spacing[6] },
  end7: { end: theme.spacing[7] },
  end8: { end: theme.spacing[8] },
  end9: { end: theme.spacing[9] },
  end10: { end: theme.spacing[10] },
  end11: { end: theme.spacing[11] },
  end12: { end: theme.spacing[12] },
  end14: { end: theme.spacing[14] },
  end16: { end: theme.spacing[16] },
  end20: { end: theme.spacing[20] },
  end24: { end: theme.spacing[24] },
  end28: { end: theme.spacing[28] },
  end32: { end: theme.spacing[32] },
  end36: { end: theme.spacing[36] },
  end40: { end: theme.spacing[40] },
  end44: { end: theme.spacing[44] },
  end48: { end: theme.spacing[48] },
  end52: { end: theme.spacing[52] },
  end56: { end: theme.spacing[56] },
  end60: { end: theme.spacing[60] },
  end64: { end: theme.spacing[64] },
  end72: { end: theme.spacing[72] },
  end80: { end: theme.spacing[80] },
  end96: { end: theme.spacing[96] },
  end1_2: { end: '50%' },
  end1_3: { end: '33.333333%' },
  end2_3: { end: '66.666667%' },
  end1_4: { end: '25%' },
  end2_4: { end: '50%' },
  end3_4: { end: '75%' },
  end1_5: { end: '20%' },
  end2_5: { end: '40%' },
  end3_5: { end: '60%' },
  end4_5: { end: '80%' },
  // Tint Color
  tintTransparent: { tintColor: theme.colors.transparent },
  tintBlack: { tintColor: theme.colors.black },
  tintWhite: { tintColor: theme.colors.white },
  // Z=Index
  // zAuto: { zIndex: "auto" },
  z0: { zIndex: 0 },
  z10: { zIndex: 10 },
  z20: { zIndex: 20 },
  z30: { zIndex: 30 },
  z40: { zIndex: 40 },
  z50: { zIndex: 50 }
}))
